# Generated by Django 5.2.8 on 2025-11-09 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_trilha', models.CharField(max_length=300, verbose_name='Nome da Trilha')),
                ('distancia_da_trilha', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Distância (km)')),
                ('tempo_de_duracao', models.DurationField(help_text='Duração da atividade (ex: 1:30:00 = 1h30min)', verbose_name='Tempo de Duração')),
                ('dificuldade', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Moderado'), (3, 'Difícil')], default=2, verbose_name='Dificuldade')),
                ('percurso_google_maps', models.URLField(blank=True, help_text='Cole aqui o link do Google Maps (rota ou localização).', null=True, verbose_name='Percurso no Google Maps')),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to='parques.parque', verbose_name='Parque')),
            ],
            options={
                'verbose_name': 'Trilha',
                'verbose_name_plural': 'Trilhas',
                'ordering': ['nome_da_trilha'],
            },
        ),
    ]
