# Generated by Django 5.2.8 on 2025-11-23 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTrilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_tag', models.CharField(max_length=300, verbose_name='Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='trilha',
            name='distancia_da_trilha',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Distância (km)'),
        ),
        migrations.AddField(
            model_name='trilha',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='trilhas', to='trilhas.tagtrilha'),
        ),
    ]
