# Generated by Django 5.2.8 on 2025-11-22 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parques', '0003_remove_parque_tag_tag_parque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Início da vigência')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Fim da vigência')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novidades', to='parques.parque', verbose_name='Parque')),
            ],
            options={
                'verbose_name': 'Novidade',
                'verbose_name_plural': 'Novidades',
                'ordering': ['titulo'],
            },
        ),
    ]
