# Generated by Django 5.2.8 on 2025-11-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novidades',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de publicação'),
        ),
    ]
