# Generated by Django 5.2.8 on 2025-11-23 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_novidades_data_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_tag', models.CharField(max_length=300, verbose_name='Tag')),
                ('novidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_novidades', to='eventos.novidades')),
            ],
        ),
    ]
