# Generated by Django 5.2.8 on 2025-11-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagNovidades',
        ),
    ]
