# Generated by Django 5.2.8 on 2025-11-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_rename_tag_tagnovidades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novidades',
            options={},
        ),
        migrations.RenameField(
            model_name='tagnovidades',
            old_name='nome_da_tag',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='tagnovidades',
            name='novidade',
        ),
        migrations.AddField(
            model_name='novidades',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='novidades', to='eventos.tagnovidades'),
        ),
    ]
