# Generated by Django 5.2.8 on 2025-11-23 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_novidades_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagnovidades',
            old_name='nome',
            new_name='nome_da_tag',
        ),
    ]
