# Generated by Django 5.2.8 on 2025-11-23 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_rename_nome_tagnovidades_nome_da_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagNovidades',
            new_name='TagNovidade',
        ),
    ]
