# Generated by Django 5.2.8 on 2025-11-23 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_rename_tagnovidades_tagnovidade'),
        ('parques', '0005_tagparque_parque_tags_delete_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Novidades',
            new_name='Novidade',
        ),
    ]
