# Generated by Django 5.2.8 on 2025-11-09 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(help_text='Formato: 00000-000', max_length=9)),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_parque', models.CharField(max_length=300, verbose_name='Nome do Parque')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parque', to='parques.endereco')),
            ],
            options={
                'verbose_name': 'Parque',
                'verbose_name_plural': 'Parques',
                'ordering': ['nome_do_parque'],
            },
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('hora_abertura', models.TimeField()),
                ('hora_fechamento', models.TimeField()),
                ('parque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='parques.parque')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'ordering': ['dia'],
            },
        ),
    ]
