# Generated by Django 5.2.8 on 2025-11-09 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_tag', models.CharField(max_length=300, verbose_name='Tag')),
            ],
        ),
        migrations.AddField(
            model_name='parque',
            name='Tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parque', to='parques.tag'),
        ),
    ]
