# Generated by Django 5.2.8 on 2025-11-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parques', '0002_tag_parque_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parque',
            name='Tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='parque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='parques.parque'),
        ),
    ]
