# Generated by Django 5.2.8 on 2025-11-23 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parques', '0003_remove_parque_tag_tag_parque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='parque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='parques.parque'),
        ),
    ]
