# Generated by Django 5.2.8 on 2025-11-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parques', '0004_alter_horariofuncionamento_parque'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagParque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_tag', models.CharField(max_length=300, unique=True, verbose_name='Tag')),
            ],
        ),
        migrations.AddField(
            model_name='parque',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='parques', to='parques.tagparque'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
