# Generated by Django 5.2.8 on 2025-11-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parques', '0005_tagparque_parque_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagparque',
            name='nome_da_tag',
            field=models.CharField(max_length=300, verbose_name='Tag'),
        ),
    ]
